version: '3'
services:
  loadbalancer:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - loadbalancer-network

networks:
  loadbalancer-network:
    driver: bridge
